CREATE TABLE IF NOT EXISTS CARD (
    CARD_ID INT PRIMARY KEY AUTO_INCREMENT,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    CARD_NUMBER VARCHAR(20) NOT NULL,
    CARD_TYPE VARCHAR(20) NOT NULL,
    TOTAL_LIMIT INT NOT NULL,
    AMOUNT_USED INT NOT NULL,
    AVAILABLE_AMOUNT INT NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);