spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # disable the default discovery routing
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "api-gateway"
    description: "API Gateway Server"
    version: "1.0.0"

logging:
  level:
    com:
      project:
        gateway: DEBUG
