services:
  accounts:
    image: "mohamedahmed412000/accounts:v1.0"
    container_name: accounts-ms
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nextgen-bank

  loans:
    image: "mohamedahmed412000/loans:v1.0"
    container_name: loans-ms
    ports:
      - "8092:8092"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nextgen-bank

  cards:
    image: "mohamedahmed412000/cards:v1.0"
    container_name: cards-ms
    ports:
      - "8093:8093"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nextgen-bank

networks:
  nextgen-bank:
    driver: bridge
