server:
  port: 8082

spring:
  application:
    name: Loans
  datasource:
    url: jdbc:h2:mem:loansDB
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true