server:
  port: 8092

spring:
  application:
    name: Loans
  datasource:
    url: jdbc:h2:mem:loansDB
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

build:
  version: 1.0

accounts:
  message: This is the customer support info for local environment
  accountInfo:
    name: John Doe - Developer
    email: john.doe@example.com
  contactList:
    - 01234567890
    - 01234567891

