server:
  port: 8092

spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:h2:mem:loansDB
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
