server:
  port: 8091

spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:accountDB
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: 1.0
