CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    CUSTOMER_ID INT NOT NULL,
    ACCOUNT_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR(100) NOT NULL,
    BRANCH_ADDRESS VARCHAR(200) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);
