spring:
  application:
    name: "Config Server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///E://Coding//Spring Projects//Microservices//configurations"
#          search-locations: "classpath:/config"

server:
  port: 8071

