global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'accounts'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['accounts:8091']
  - job_name: 'cards'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'cards:8093' ]
  - job_name: 'loans'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['loans:8092']
  - job_name: 'configserver'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'config-server:8071' ]
  - job_name: 'eurekaserver'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8070']
  - job_name: 'apigateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api-gateway:8080' ]
