global:
  configMapName: nextgen-bank-dev-configmap
  activeProfile: prod
  configServerURL: configserver:http://config-server:8071/
  eurekaServerURL: http://eureka-server:8070/eureka/
  keycloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-2.14.0.jar"
  otelExporterEndpoint: http://tempo-grafana-tempo-distributor:4318
  otelMetricsEndpoint: none
  otelLogsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
  redisServerURL: redis-master.default.svc.cluster.local