services:
  network-deploy-service:
    networks:
      - nextgen-bank

  db-base:
    image: mysql
    extends:
      service: network-deploy-service
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 10s
      retries: 10
      interval: 10s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  microservice-base:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  configserver-deploy-base:
    extends:
      service: microservice-base
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
