services:
  config-server:
    image: "mohamedahmed412000/config-server:v2.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8071/actuator/health/readiness"]
      #      start the test after 10 seconds and if failed then retry 10 times with interval of 10 seconds
      #      between tests with maximum timeout for every test as 5 seconds
      start_period: 10s
      retries: 10
      interval: 10s
      timeout: 5s
    restart: unless-stopped
    extends:
      file: common-services.yml
      service: microservice-base

  accounts:
    image: "mohamedahmed412000/accounts:v3.0"
    container_name: accounts-ms
    ports:
      - "8091:8091"
    depends_on:
      config-server:
        condition: service_healthy
      accounts-db:
        condition: service_healthy
    extends:
      file: common-services.yml
      service: configserver-deploy-base
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accounts-db:3306/accounts-db"

  accounts-db:
    container_name: accounts-db
    environment:
      MYSQL_DATABASE: "accounts-db"
    ports:
      - "3306:3306"
    extends:
      file: common-services.yml
      service: db-base

  loans:
    image: "mohamedahmed412000/loans:v3.0"
    container_name: loans-ms
    ports:
      - "8092:8092"
    depends_on:
      config-server:
        condition: service_healthy
      loans-db:
        condition: service_healthy
    extends:
      file: common-services.yml
      service: configserver-deploy-base
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loans-db:3306/loans-db"

  loans-db:
    container_name: loans-db
    environment:
      MYSQL_DATABASE: "loans-db"
    ports:
      - "3308:3306"
    extends:
      file: common-services.yml
      service: db-base

  cards:
    image: "mohamedahmed412000/cards:v3.0"
    container_name: cards-ms
    ports:
      - "8093:8093"
    depends_on:
      config-server:
        condition: service_healthy
      cards-db:
        condition: service_healthy
    extends:
      file: common-services.yml
      service: configserver-deploy-base
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cards-db:3306/cards-db"

  cards-db:
    container_name: cards-db
    environment:
      MYSQL_DATABASE: "cards-db"
    ports:
      - "3307:3306"
    extends:
      file: common-services.yml
      service: db-base

networks:
  nextgen-bank:
    driver: bridge
